---
# defaults file for post-install
usernames:
- user11
- user12
- user13
- user14


ntp0: 0.north-america.pool.ntp.org iburst
ntp1: 1.north-america.pool.ntp.org iburst
ntp2: 2.north-america.pool.ntp.org iburst
ntp3: 3.north-america.pool.ntp.org iburst
  
ntp_path: /etc/ntp.conf
