- name: Provisioning server
  hosts: all
  become: yes
  vars:
    ntp_path: /etc/ntp.conf
  tasks:
    - name: Install NTP on Centos
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP on Ubuntu OS
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start and enable NTP on Centos
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"


    - name: Starte and enable NTP on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add group
      group:
        name: devops
        state: present

    - name: Add users
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop: "{{usernames}}"

    - name: Banner file /etc/motd
      copy:
        content: "This {{ansible_distribution}} is managed by Ansible \n"
        dest: /etc/motd

    - name: Deploy NTP conf file for redhat
      template:
        src: templates/ntp_redhat.j2
        dest: "{{ntp_path}}"
      when: ansible_os_family == "RedHat"
      notify: Restart NTPD service for redhat

    - name: Deploy NTP conf file for debian
      template:
        src: templates/ntp_debian.j2
        dest: "{{ntp_path}}"
      when: ansible_os_family == "Debian"
      notify: Restart NTP service for debian

    - name: Directory for dev data
      file:
        path: /opt/devdata
        state: directory
        mode: 0775

    - name: Deploy dev data file
      copy:
        src: files/dev.txt
        dest: /opt/devdata/dev.txt


  handlers:
    - name: Restart NTPD service for redhat
      service:
        name: ntpd
        state: restarted
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Restart NTP service for debian
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_os_family == "Debian"



          
