- name: Setup Webserver
  hosts: websrvrgrp
  become: yes
  tasks:
    - name: Install apache httpd
      yum:
        name: httpd
        state: present
    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Hosting the index.html file through httpd
      copy:
        src: index.html
        dest: /var/www/html/index.html

- name: Setup database server
  hosts: dbsrvrgrp
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
        name: MySQL-python.x86_64
        state: present

    - name: Install Python MySQL
      yum:
        name: mariadb-server
        state: present
    - name: Start and enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
          
    - name: Create a new database with name 'bobdata'
      mysql_db:
        name: bobdata
        state: present
