- name: Setup database server
  hosts: dbsrvrgrp
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present

    - name: Install Python MySQL
      yum:
        name: MySQL-python.x86_64
        state: present
    - name: Start and enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
            
    - name: Create a new database with name 'account'
      mysql_db:
        name: accounts
        state: present
    - name: Create database user with name 'admin' 
      mysql_user:
        name: admin
        password: 12345
        priv: '*.*:ALL'
        state: present
